# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.58377531, 0.03094453, 0.04946788, 0.99280569, 0.69402122],
        [0.55098232, 0.93606601, 0.00376728, 0.07280013, 0.22987187],
        [0.68951966, 0.24426489, 0.74802779, 0.46028357, 0.53438305]],

       [[0.67493768, 0.74443238, 0.65898676, 0.33585867, 0.50475207],
        [0.27152576, 0.66914459, 0.25170456, 0.6285859 , 0.26456595],
        [0.28669227, 0.63485959, 0.30192509, 0.04882859, 0.90121308]]])

In [5]:
# Method 2
a = np.random.randint(1, 100, size=(2,3,5))
a

array([[[59, 80, 58, 64, 15],
        [31, 91, 54, 34, 77],
        [54, 52, 85, 28, 95]],

       [[78, 17, 36, 55, 73],
        [ 2, 18,  9, 61, 52],
        [51,  6, 52, 44, 85]]])

In [6]:
# Method 3


#### 4. Print *a*.


    When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
        the last axis is printed from left to right,
        the second-to-last is printed from top to bottom,
        the rest are also printed from top to bottom, with each slice separated from the next by an empty line.
        One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices

In [7]:
# your code here
print(a) 

[[[59 80 58 64 15]
  [31 91 54 34 77]
  [54 52 85 28 95]]

 [[78 17 36 55 73]
  [ 2 18  9 61 52]
  [51  6 52 44 85]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b= np.ones((5,2,3))


#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here

a.size == b.size


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here
#to add two numpy they must have the same shape
a.shape, b.shape




((2, 3, 5), (5, 2, 3))

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here

c = np.transpose (b).reshape(2,3,5)
print(c)

c.shape



[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here
d = a + c
print(d)

[[[60. 81. 59. 65. 16.]
  [32. 92. 55. 35. 78.]
  [55. 53. 86. 29. 96.]]

 [[79. 18. 37. 56. 74.]
  [ 3. 19. 10. 62. 53.]
  [52.  7. 53. 45. 86.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
# your code/answer here
print(a)
print(d)

[[[59 80 58 64 15]
  [31 91 54 34 77]
  [54 52 85 28 95]]

 [[78 17 36 55 73]
  [ 2 18  9 61 52]
  [51  6 52 44 85]]]
[[[60. 81. 59. 65. 16.]
  [32. 92. 55. 35. 78.]
  [55. 53. 86. 29. 96.]]

 [[79. 18. 37. 56. 74.]
  [ 3. 19. 10. 62. 53.]
  [52.  7. 53. 45. 86.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
# your code here
e = np.multiply(a,c)
e

array([[[59., 80., 58., 64., 15.],
        [31., 91., 54., 34., 77.],
        [54., 52., 85., 28., 95.]],

       [[78., 17., 36., 55., 73.],
        [ 2., 18.,  9., 61., 52.],
        [51.,  6., 52., 44., 85.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = round(np.mean(d),2)
print(d)

print("\nThe maximum value in this array is: ", str(d_max)+"\nThe minimum value in this array is:",str(d_min),"\nThe mean of this array is:", str(d_mean))

[[[60. 81. 59. 65. 16.]
  [32. 92. 55. 35. 78.]
  [55. 53. 86. 29. 96.]]

 [[79. 18. 37. 56. 74.]
  [ 3. 19. 10. 62. 53.]
  [52.  7. 53. 45. 86.]]]

The maximum value in this array is:  96.0
The minimum value in this array is: 3.0 
The mean of this array is: 51.53


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
# your code here
import numpy as np
f = np.empty((2,3,5))
print(f)
print(f[0,0,1])

[[[60. 81. 59. 65. 16.]
  [32. 92. 55. 35. 78.]
  [55. 53. 86. 29. 96.]]

 [[79. 18. 37. 56. 74.]
  [ 3. 19. 10. 62. 53.]
  [52.  7. 53. 45. 86.]]]
81.0


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [19]:
len(f[0])

3

In [23]:

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d_min < k and k < d_mean:
                f[i][j][k] = 25
            if d_mean < k and k < d_max:
                f[i][j][k] = 75
            if k == d_min:
                f[i][j][k] = 0
            if k == d_mean:
                f[i][j][k] = 50
            if k == d_max:
                f[i][j][k] = 100
                
print(d_min, d_mean, d_max)
print('d', d)
print('f', f)

3.0 51.53 96.0
d [[[60. 81. 59. 65. 16.]
  [32. 92. 55. 35. 78.]
  [55. 53. 86. 29. 96.]]

 [[79. 18. 37. 56. 74.]
  [ 3. 19. 10. 62. 53.]
  [52.  7. 53. 45. 86.]]]
f [[[25. 25. 25.  0. 25.]
  [25. 25. 25.  0. 25.]
  [25. 25. 25.  0. 25.]]

 [[25. 25. 25.  0. 25.]
  [ 3. 25. 25.  0. 25.]
  [25. 25. 25.  0. 25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [22]:
# your code here
print("if d is:")
print(d)
print("\nf is:")
print(f)

if d is:
[[[60. 81. 59. 65. 16.]
  [32. 92. 55. 35. 78.]
  [55. 53. 86. 29. 96.]]

 [[79. 18. 37. 56. 74.]
  [ 3. 19. 10. 62. 53.]
  [52.  7. 53. 45. 86.]]]

f is:
[[[60. 81. 59.  0. 25.]
  [32. 92. 55.  0. 25.]
  [55. 53. 86.  0. 25.]]

 [[79. 18. 37.  0. 25.]
  [ 3. 19. 10.  0. 25.]
  [52.  7. 53.  0. 25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [26]:
# your code here
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):           
            if k == d_min:
                f[i][j][k] = "A"
            if d_min < k < d_mean:
                f[i][j][k] = "B"
            if k == d_mean:
                f[i][j][k] = "C"
            if d_mean < k < d_max:
                f[i][j][k] = "D"
            if k == d_max:
                f[i][j][k] = "E"
print(d_min, d_mean, d_max)
print("if d is:")
print(d)
print("\nf is:")
print(f)

5.0 44.17 99.0
if d is:
[[[49. 72. 19. 28. 80.]
  [16. 59. 74. 30. 77.]
  [84. 99. 30. 97. 29.]]

 [[61.  5.  7. 49. 31.]
  [45. 37. 20. 26. 20.]
  [61. 45. 45. 17. 13.]]]

f is:
[[[49. 72. 19. 28. 80.]
  [16. 59. 74. 30. 77.]
  [84. 99. 30. 97. 29.]]

 [[61.  5.  7. 49. 31.]
  [45. 37. 20. 26. 20.]
  [61. 45. 45. 17. 13.]]]
